name: Build cadmium images
on: [push, workflow_dispatch]
jobs:

  build-debian-arm-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm64-debian
        run: |
          ls
          cp cadmium-configs/config-arm64-debian config
          sudo ./build-all arm64-debian.img 2G
       
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm64-debian
          path: arm64-debian.img

  build-debian-arm-32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm32-debian
        run: |
          ls
          cp cadmium-configs/config-arm32-debian config
          sudo ./build-all arm32-debian.img 2G
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm32-debian
          path: arm32-debian.img

  build-arch-arm-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm64-arch
        run: |
          ls
          cp cadmium-configs/config-arm64-arch config
          sudo ./build-all arm64-arch.img 3G
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm64-arch
          path: arm64-arch.img

  build-arch-arm-32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm32-arch
        run: |
          ls
          cp cadmium-configs/config-arm32-arch config
          sudo ./build-all arm32-arch.img 3G
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm32-arch
          path: arm32-arch.img   

  build-void-arm-64:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: set up environment
       run: |
         cd $GITHUB_WORKSPACE
         echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
         sudo apt update
         sudo apt install -y libunwind-dev
         sudo apt build-dep linux
         sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
         
     - name: remove existing config
       run: |
         rm config
         
     - name: build arm64-void
       run: |
         ls
         cp cadmium-configs/config-arm64-void config
         sudo ./build-all arm64-void.img 3G
     - name: Upload artifacts
       uses: actions/upload-artifact@v2.2.2
       with:
         name: arm64-void
         path: arm64-void.img    

  build-void-arm-32:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: set up environment
       run: |
         cd $GITHUB_WORKSPACE
         echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
         sudo apt update
         sudo apt install -y libunwind-dev
         sudo apt build-dep linux
         sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
         
     - name: remove existing config
       run: |
         rm config
         
     - name: build arm32-void
       run: |
         ls
         cp cadmium-configs/config-arm32-void config
         sudo ./build-all arm32-void.img 3G
     - name: Upload artifacts
       uses: actions/upload-artifact@v2.2.2
       with:
         name: arm32-void
         path: arm32-void.img

  build-void-musl-arm-64:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: set up environment
       run: |
         cd $GITHUB_WORKSPACE
         echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
         sudo apt update
         sudo apt install -y libunwind-dev
         sudo apt build-dep linux
         sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
         
     - name: remove existing config
       run: |
         rm config
         
     - name: build arm64-void-musl
       run: |
         ls
         cp cadmium-configs/config-arm64-void-musl config
         sudo ./build-all arm64-void-musl.img 3G
     - name: Upload artifacts
       uses: actions/upload-artifact@v2.2.2
       with:
         name: arm64-void-musl
         path: arm64-void-musl.img    

  build-void-musl-arm-32:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: set up environment
       run: |
         cd $GITHUB_WORKSPACE
         echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
         sudo apt update
         sudo apt install -y libunwind-dev
         sudo apt build-dep linux
         sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
         
     - name: remove existing config
       run: |
         rm config
         
     - name: build arm32-void-musl
       run: |
         ls
         cp cadmium-configs/config-arm32-void-musl config
         sudo ./build-all arm32-void-musl.img 3G
     - name: Upload artifacts
       uses: actions/upload-artifact@v2.2.2
       with:
         name: arm32-void-musl
         path: arm32-void-musl.img   
